#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App2.Resource", IsApplication=true)]

namespace App2
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::App2.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::App2.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::App2.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int colorAccent = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int colorPrimary = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int colorPrimaryDark = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int ic_launcher_background = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int logo2 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int qrcode = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070012
			public const int HeightPicker = 2131165202;
			
			// aapt resource value: 0x7f070011
			public const int WeightPicker = 2131165201;
			
			// aapt resource value: 0x7f07000b
			public const int accImg = 2131165195;
			
			// aapt resource value: 0x7f070010
			public const int agePicker = 2131165200;
			
			// aapt resource value: 0x7f070009
			public const int caloriesTxt = 2131165193;
			
			// aapt resource value: 0x7f07001d
			public const int contentFrame = 2131165213;
			
			// aapt resource value: 0x7f070014
			public const int gridLayout2 = 2131165204;
			
			// aapt resource value: 0x7f07001b
			public const int historyBtn = 2131165211;
			
			// aapt resource value: 0x7f070002
			public const int loginBtn = 2131165186;
			
			// aapt resource value: 0x7f07001c
			public const int logoutBtn = 2131165212;
			
			// aapt resource value: 0x7f070008
			public const int repsTxt = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int sessionTxt = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int sessionsList = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int setsTxt = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int signupBtn = 2131165187;
			
			// aapt resource value: 0x7f07000a
			public const int speedImg = 2131165194;
			
			// aapt resource value: 0x7f070019
			public const int startTrainingBtn = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int stopTrainingBtn = 2131165210;
			
			// aapt resource value: 0x7f070006
			public const int timeTxt = 2131165190;
			
			// aapt resource value: 0x7f07000c
			public const int txtFirstName = 2131165196;
			
			// aapt resource value: 0x7f070013
			public const int txtHello = 2131165203;
			
			// aapt resource value: 0x7f07000d
			public const int txtLastName = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int txtPass = 2131165199;
			
			// aapt resource value: 0x7f070001
			public const int txtPassword = 2131165185;
			
			// aapt resource value: 0x7f070017
			public const int txtRepsSet = 2131165207;
			
			// aapt resource value: 0x7f070016
			public const int txtSets = 2131165206;
			
			// aapt resource value: 0x7f070015
			public const int txtTimer = 2131165205;
			
			// aapt resource value: 0x7f070018
			public const int txtTotalReps = 2131165208;
			
			// aapt resource value: 0x7f07000e
			public const int txtUser = 2131165198;
			
			// aapt resource value: 0x7f070000
			public const int txtUserName = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int history_activity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int imageVis = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int signup = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int user_activity = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int zxingscanneractivitylayout = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int zxingscannerfragmentlayout = 2130968582;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ic_launcher_foreground = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ic_launcher_round = 2130903042;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int action_settings = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
